---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fleet.pkarakal.com
  resources:
  - collectorgroupbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.pkarakal.com
  resources:
  - collectorgroupbindings/finalizers
  verbs:
  - update
- apiGroups:
  - fleet.pkarakal.com
  resources:
  - collectorgroupbindings/status
  verbs:
  - get
  - patch
  - update
