# Copyright 2026 Pavlos Karakalidis
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alloy-remote-config
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
